# Generated by Django 3.2.9 on 2021-12-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('film_poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Постер к фильму')),
                ('film_description', models.TextField(blank=True, null=True, verbose_name='Описание к фильму')),
                ('film_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_catalog.category', verbose_name='Категория фильма')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_title', models.CharField(max_length=255, verbose_name='Название сериала')),
                ('serial_poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Постер к сериалу')),
                ('serial_description', models.TextField(blank=True, null=True, verbose_name='Описание к сериалу')),
                ('series_watch', models.IntegerField(blank=True, default=0, verbose_name='Просмотренные серии')),
                ('series_max', models.IntegerField(blank=True, verbose_name='Максимальное количество серий')),
                ('serial_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_catalog.category', verbose_name='Категория сериала')),
                ('serial_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_catalog.genre', verbose_name='Жанр сериала')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default=None, max_length=255, verbose_name='Название статуса')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('login', models.CharField(max_length=100, verbose_name='Логин пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='SerialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.serial', verbose_name='Сериал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SerialGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.genre', verbose_name='Жанры')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.serial', verbose_name='Сериал')),
            ],
        ),
        migrations.CreateModel(
            name='SerialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.category', verbose_name='Категории')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.serial', verbose_name='Сериал')),
            ],
        ),
        migrations.AddField(
            model_name='serial',
            name='serial_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_catalog.status', verbose_name='Статус сериала'),
        ),
        migrations.CreateModel(
            name='FilmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.film', verbose_name='Фильм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.film', verbose_name='Фильм')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.genre', verbose_name='Жанры')),
            ],
        ),
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.category', verbose_name='Категории')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_catalog.film', verbose_name='Фильм')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='film_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_catalog.genre', verbose_name='Жанр фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_catalog.status', verbose_name='Статус фильма'),
        ),
    ]
